export const sampleData = [
  {
    firstName: 'discovery',
    age: 24,
    visits: 11,
    progress: 43,
    status: 'complicated',
  },
  {
    firstName: 'penalty',
    age: 29,
    visits: 25,
    progress: 7,
    status: 'single',
  },
  {
    firstName: 'expansion',
    age: 15,
    visits: 17,
    progress: 78,
    status: 'relationship',
  },
  {
    firstName: 'confusion',
    age: 0,
    visits: 89,
    progress: 10,
    status: 'complicated',
  },
];

export const data = [
  {
    firstName: 'discovery',
    age: 24,
    visits: 11,
    progress: 43,
    status: 'complicated',
  },
  {
    firstName: 'penalty',
    age: 29,
    visits: 25,
    progress: 7,
    status: 'single',
  },
  {
    firstName: 'expansion',
    age: 15,
    visits: 17,
    progress: 78,
    status: 'relationship',
  },
  {
    firstName: 'confusion',
    age: 0,
    visits: 89,
    progress: 10,
    status: 'complicated',
  },
  {
    firstName: 'club',
    age: 0,
    visits: 80,
    progress: 23,
    status: 'relationship',
  },
  {
    firstName: 'spark',
    age: 12,
    visits: 3,
    progress: 13,
    status: 'single',
  },
  {
    firstName: 'assistant',
    age: 20,
    visits: 10,
    progress: 22,
    status: 'relationship',
  },
  {
    firstName: 'twist',
    age: 5,
    visits: 22,
    progress: 48,
    status: 'complicated',
  },
  {
    firstName: 'birthday',
    age: 23,
    visits: 66,
    progress: 52,
    status: 'single',
  },
  {
    firstName: 'bucket',
    age: 15,
    visits: 33,
    progress: 40,
    status: 'relationship',
  },
  {
    firstName: 'attention',
    age: 6,
    visits: 97,
    progress: 43,
    status: 'single',
  },
  {
    firstName: 'literature',
    age: 24,
    visits: 64,
    progress: 73,
    status: 'complicated',
  },
  {
    firstName: 'obligation',
    age: 24,
    visits: 29,
    progress: 89,
    status: 'single',
  },
  {
    firstName: 'feather',
    age: 21,
    visits: 31,
    progress: 2,
    status: 'complicated',
  },
  {
    firstName: 'land',
    age: 3,
    visits: 15,
    progress: 31,
    status: 'complicated',
  },
  {
    firstName: 'story',
    age: 8,
    visits: 62,
    progress: 13,
    status: 'complicated',
  },
  {
    firstName: 'judgment',
    age: 20,
    visits: 5,
    progress: 53,
    status: 'single',
  },
  {
    firstName: 'comparison',
    age: 27,
    visits: 69,
    progress: 32,
    status: 'single',
  },
  {
    firstName: 'comfort',
    age: 9,
    visits: 68,
    progress: 70,
    status: 'relationship',
  },
  {
    firstName: 'bone',
    age: 16,
    visits: 96,
    progress: 65,
    status: 'complicated',
  },
  {
    firstName: 'coal',
    age: 23,
    visits: 7,
    progress: 99,
    status: 'complicated',
  },
  {
    firstName: 'extent',
    age: 16,
    visits: 76,
    progress: 4,
    status: 'complicated',
  },
  {
    firstName: 'president',
    age: 2,
    visits: 88,
    progress: 46,
    status: 'relationship',
  },
  {
    firstName: 'memory',
    age: 17,
    visits: 1,
    progress: 93,
    status: 'complicated',
  },
  {
    firstName: 'zipper',
    age: 29,
    visits: 95,
    progress: 45,
    status: 'relationship',
  },
  {
    firstName: 'hearing',
    age: 10,
    visits: 61,
    progress: 27,
    status: 'relationship',
  },
  {
    firstName: 'silver',
    age: 15,
    visits: 11,
    progress: 60,
    status: 'complicated',
  },
  {
    firstName: 'cable',
    age: 23,
    visits: 46,
    progress: 68,
    status: 'complicated',
  },
  {
    firstName: 'doll',
    age: 6,
    visits: 8,
    progress: 2,
    status: 'single',
  },
  {
    firstName: 'shop',
    age: 13,
    visits: 15,
    progress: 79,
    status: 'single',
  },
];
